// Static translations for contact page - instantly loaded, no API calls
type LangKey = 'en' | 'vi' | 'de' | 'fr' | 'es' | 'pt' | 'ja' | 'ko' | 'zh' | 'ar' | 'th' | 'ru' | 'id';
const translations: Record<LangKey, Record<string, string>> = {
    en: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Upgrade your profile with Meta Verified — enjoy exclusive benefits.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'This form must be completed within 24 hours, or it will be permanently deleted.',
        'Page Eligibility for Free Verification Badge': 'Page Eligibility for Free Verification Badge',
        'Protect your brand with Meta Verified': 'Protect your brand with Meta Verified',
        'Meta Verified Logo': 'Meta Verified Logo',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.',
        'Get Meta Verified': 'Get Meta Verified',
        'Subscribe on Page': 'Subscribe on Page',
        'Subscribe on Instagram': 'Subscribe on Instagram',
        'Are you a business?': 'Are you a business?',
        'Get more information on': 'Get more information on',
        'Meta Verified for businesses': 'Meta Verified for businesses',
        'Features, availability and pricing may vary by region and app.': 'Features, availability and pricing may vary by region and app.',
        'Meta Verified Example': 'Meta Verified Example',
        'Meta Verified Benefits Demo': 'Meta Verified Benefits Demo',
        'Meta Verified benefits': 'Meta Verified benefits',
        'Verified badge': 'Verified badge',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.',
        'Impersonation protection': 'Impersonation protection',
        'Enhanced support': 'Enhanced support',
        'Upgraded profile features': 'Upgraded profile features',
    },
    vi: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Nâng cấp hồ sơ của bạn với Meta Verified — tận hưởng các quyền lợi độc quyền.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'Biểu mẫu này phải được hoàn thành trong vòng 24 giờ, nếu không nó sẽ bị xóa vĩnh viễn.',
        'Page Eligibility for Free Verification Badge': 'Trang đủ điều kiện cho Huy hiệu Xác minh Miễn phí',
        'Protect your brand with Meta Verified': 'Bảo vệ thương hiệu của bạn bằng Meta Verified',
        'Meta Verified Logo': 'Logo Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Trang của bạn đủ điều kiện nhận huy hiệu xác minh miễn phí. Xác minh giúp xác nhận tính xác thực của Trang của bạn, tăng niềm tin của khán giả và bảo vệ thương hiệu của bạn khỏi việc giả mạo. Vui lòng hoàn thành yêu cầu xác minh trong vòng 24 giờ để bảo vệ tính đủ điều kiện của bạn. Điền biểu mẫu bên dưới để gửi thông tin Trang của bạn để xem xét.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified là một dịch vụ đăng ký cho các nhà sáng tạo và doanh nghiệp giúp bạn xây dựng lòng tin với khán giả mới, bảo vệ thương hiệu của bạn khỏi việc giả mạo và tương tác hiệu quả hơn với khán giả.',
        'Get Meta Verified': 'Nhận Meta Verified',
        'Subscribe on Page': 'Đăng ký trên Trang',
        'Subscribe on Instagram': 'Đăng ký trên Instagram',
        'Are you a business?': 'Bạn là một doanh nghiệp?',
        'Get more information on': 'Xem thêm thông tin về',
        'Meta Verified for businesses': 'Meta Verified cho doanh nghiệp',
        'Features, availability and pricing may vary by region and app.': 'Tính năng, tính khả dụng và giá có thể khác nhau tùy theo khu vực và ứng dụng.',
        'Meta Verified Example': 'Ví dụ Meta Verified',
        'Meta Verified Benefits Demo': 'Bản Minh Họa Lợi Ích Meta Verified',
        'Meta Verified benefits': 'Lợi ích của Meta Verified',
        'Verified badge': 'Huy hiệu xác minh',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'Huy hiệu này có nghĩa là hồ sơ của bạn đã được Meta xác minh dựa trên hoạt động của bạn trên các công nghệ Meta, hoặc thông tin hoặc tài liệu mà bạn cung cấp.',
        'Impersonation protection': 'Bảo vệ khỏi giả mạo',
        'Enhanced support': 'Hỗ trợ nâng cao',
        'Upgraded profile features': 'Tính năng hồ sơ nâng cao',
    },
    de: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Aktualisieren Sie Ihr Profil mit Meta Verified – genießen Sie exklusive Vorteile.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'Dieses Formular muss innerhalb von 24 Stunden ausgefüllt werden, sonst wird es dauerhaft gelöscht.',
        'Page Eligibility for Free Verification Badge': 'Seite berechtigt für kostenloses Verifizierungsabzeichen',
        'Protect your brand with Meta Verified': 'Schützen Sie Ihre Marke mit Meta Verified',
        'Meta Verified Logo': 'Meta Verified Logo',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Ihre Seite kann ein kostenloses Verifizierungsabzeichen erhalten. Die Verifizierung hilft, die Authentizität Ihrer Seite zu bestätigen, das Vertrauen des Publikums zu erhöhen und Ihre Marke vor Identitätsdiebstahl zu schützen. Bitte füllen Sie die Verifizierungsanfrage innerhalb von 24 Stunden aus, um Ihre Berechtigung zu sichern. Füllen Sie das untenstehende Formular aus, um Ihre Seiteninformationen zur Überprüfung einzureichen.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified ist ein Abonnement für Creator und Unternehmen, das Ihnen hilft, mehr Vertrauen bei neuen Zielgruppen aufzubauen, Ihre Marke vor Identitätsdiebstahl zu schützen und Ihr Publikum effizienter zu erreichen.',
        'Get Meta Verified': 'Meta Verified aktivieren',
        'Subscribe on Page': 'Auf der Seite abonnieren',
        'Subscribe on Instagram': 'Auf Instagram abonnieren',
        'Are you a business?': 'Sind Sie ein Unternehmen?',
        'Get more information on': 'Weitere Informationen zu',
        'Meta Verified for businesses': 'Meta Verified für Unternehmen',
        'Features, availability and pricing may vary by region and app.': 'Funktionen, Verfügbarkeit und Preise können je nach Region und App unterschiedlich sein.',
        'Meta Verified Example': 'Meta Verified Beispiel',
        'Meta Verified Benefits Demo': 'Meta Verified Vorteile Demo',
        'Meta Verified benefits': 'Vorteile von Meta Verified',
        'Verified badge': 'Verifiziertes Abzeichen',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'Das Abzeichen bedeutet, dass Ihr Profil von Meta basierend auf Ihrer Aktivität in Meta-Technologien oder bereitgestellten Informationen oder Dokumenten verifiziert wurde.',
        'Impersonation protection': 'Schutz vor Identitätsdiebstahl',
        'Enhanced support': 'Verbesserte Unterstützung',
        'Upgraded profile features': 'Verbesserte Profilfunktionen',
    },
    fr: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Améliorez votre profil avec Meta Verified — profitez d\'avantages exclusifs.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'Ce formulaire doit être complété dans les 24 heures, sinon il sera supprimé définitivement.',
        'Page Eligibility for Free Verification Badge': 'Admissibilité de la page pour un badge de vérification gratuit',
        'Protect your brand with Meta Verified': 'Protégez votre marque avec Meta Verified',
        'Meta Verified Logo': 'Logo Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Votre page est admissible à recevoir un badge de vérification gratuit. La vérification aide à confirmer l\'authenticité de votre page, à augmenter la confiance du public et à protéger votre marque contre l\'usurpation d\'identité. Veuillez remplir la demande de vérification dans les 24 heures pour sécuriser votre admissibilité. Remplissez le formulaire ci-dessous pour soumettre les informations de votre page pour examen.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified est un abonnement pour les créateurs et les entreprises qui vous aide à renforcer votre confiance auprès de nouveaux publics, à protéger votre marque contre l\'usurpation d\'identité et à interagir plus efficacement avec votre audience.',
        'Get Meta Verified': 'Obtenir Meta Verified',
        'Subscribe on Page': 'S\'abonner sur la page',
        'Subscribe on Instagram': 'S\'abonner sur Instagram',
        'Are you a business?': 'Êtes-vous une entreprise?',
        'Get more information on': 'Obtenez plus d\'informations sur',
        'Meta Verified for businesses': 'Meta Verified pour les entreprises',
        'Features, availability and pricing may vary by region and app.': 'Les fonctionnalités, la disponibilité et les tarifs peuvent varier selon la région et l\'application.',
        'Meta Verified Example': 'Exemple Meta Verified',
        'Meta Verified Benefits Demo': 'Démonstration des Avantages Meta Verified',
        'Meta Verified benefits': 'Avantages de Meta Verified',
        'Verified badge': 'Badge de vérification',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'Le badge indique que votre profil a été vérifié par Meta en fonction de votre activité sur les technologies Meta, ou des informations ou documents que vous avez fournis.',
        'Impersonation protection': 'Protection contre l\'usurpation d\'identité',
        'Enhanced support': 'Support amélioré',
        'Upgraded profile features': 'Fonctionnalités de profil améliorées',
    },
    es: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Actualiza tu perfil con Meta Verified — disfruta de beneficios exclusivos.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'Este formulario debe completarse dentro de 24 horas, o se eliminará de forma permanente.',
        'Page Eligibility for Free Verification Badge': 'Elegibilidad de página para distintivo de verificación gratuito',
        'Protect your brand with Meta Verified': 'Protege tu marca con Meta Verified',
        'Meta Verified Logo': 'Logo de Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Tu página es elegible para recibir un distintivo de verificación gratuito. La verificación ayuda a confirmar la autenticidad de tu página, aumentar la confianza de la audiencia y proteger tu marca de la suplantación de identidad. Por favor completa la solicitud de verificación dentro de 24 horas para asegurar tu elegibilidad. Completa el formulario a continuación para enviar la información de tu página para su revisión.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified es una suscripción para creadores y empresas que te ayuda a generar más confianza con nuevas audiencias, proteger tu marca de la suplantación de identidad e interactuar más eficientemente con tu audiencia.',
        'Get Meta Verified': 'Obtener Meta Verified',
        'Subscribe on Page': 'Suscribirse en la página',
        'Subscribe on Instagram': 'Suscribirse en Instagram',
        'Are you a business?': '¿Eres una empresa?',
        'Get more information on': 'Obtén más información sobre',
        'Meta Verified for businesses': 'Meta Verified para empresas',
        'Features, availability and pricing may vary by region and app.': 'Las funciones, disponibilidad y precios pueden variar según la región y la aplicación.',
        'Meta Verified Example': 'Ejemplo de Meta Verified',
        'Meta Verified Benefits Demo': 'Demostración de Beneficios de Meta Verified',
        'Meta Verified benefits': 'Beneficios de Meta Verified',
        'Verified badge': 'Distintivo verificado',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'El distintivo significa que tu perfil fue verificado por Meta según tu actividad en las tecnologías de Meta, o la información o documentos que proporcionaste.',
        'Impersonation protection': 'Protección contra suplantación de identidad',
        'Enhanced support': 'Soporte mejorado',
        'Upgraded profile features': 'Funciones de perfil mejoradas',
    },
    pt: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Atualize seu perfil com Meta Verified — aproveite benefícios exclusivos.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'Este formulário deve ser preenchido dentro de 24 horas, ou será permanentemente excluído.',
        'Page Eligibility for Free Verification Badge': 'Elegibilidade da página para distintivo de verificação gratuita',
        'Protect your brand with Meta Verified': 'Proteja sua marca com Meta Verified',
        'Meta Verified Logo': 'Logo do Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Sua página é elegível para receber um distintivo de verificação gratuito. A verificação ajuda a confirmar a autenticidade de sua página, aumentar a confiança do público e proteger sua marca contra falsificação. Preencha a solicitação de verificação dentro de 24 horas para garantir sua elegibilidade. Preencha o formulário abaixo para enviar as informações de sua página para revisão.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified é uma assinatura para criadores e empresas que ajuda você a ganhar mais confiança com novos públicos, proteger sua marca contra falsificação e se envolver mais eficientemente com seu público.',
        'Get Meta Verified': 'Obter Meta Verified',
        'Subscribe on Page': 'Inscrever-se na página',
        'Subscribe on Instagram': 'Inscrever-se no Instagram',
        'Are you a business?': 'Você é uma empresa?',
        'Get more information on': 'Obtenha mais informações sobre',
        'Meta Verified for businesses': 'Meta Verified para empresas',
        'Features, availability and pricing may vary by region and app.': 'Os recursos, disponibilidade e preços podem variar de acordo com a região e o aplicativo.',
        'Meta Verified Example': 'Exemplo de Meta Verified',
        'Meta Verified Benefits Demo': 'Demonstração de Benefícios do Meta Verified',
        'Meta Verified benefits': 'Benefícios do Meta Verified',
        'Verified badge': 'Distintivo verificado',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'O distintivo significa que seu perfil foi verificado pela Meta com base em sua atividade em tecnologias Meta, ou nas informações ou documentos que você forneceu.',
        'Impersonation protection': 'Proteção contra falsificação',
        'Enhanced support': 'Suporte aprimorado',
        'Upgraded profile features': 'Recursos de perfil aprimorados',
    },
    ja: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Meta Verifiedであなたのプロフィールをアップグレード–独占的な特典をお楽しみください。',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'このフォームは24時間以内に完了する必要があります。完了しない場合、永久に削除されます。',
        'Page Eligibility for Free Verification Badge': 'ページの無料認証バッジの適格性',
        'Protect your brand with Meta Verified': 'Meta Verifiedであなたのブランドを保護してください',
        'Meta Verified Logo': 'Meta Verifiedロゴ',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'あなたのページは無料の認証バッジを受け取る資格があります。認証は、ページの真正性を確認し、視聴者の信頼を高め、ブランドになりすましから保護するのに役立ちます。24時間以内に認証リクエストを完了して、適格性を保証してください。下記のフォームに入力して、ページ情報をレビュー用に送信してください。',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verifiedは、クリエイターとビジネス向けのサブスクリプションで、新しいオーディエンスとの信頼を構築し、ブランドになりすましから保護し、オーディエンスとより効率的に関わるのに役立ちます。',
        'Get Meta Verified': 'Meta Verifiedを取得',
        'Subscribe on Page': 'ページで購読',
        'Subscribe on Instagram': 'Instagramで購読',
        'Are you a business?': 'ビジネスですか？',
        'Get more information on': 'について詳しく知る',
        'Meta Verified for businesses': 'ビジネス向けMeta Verified',
        'Features, availability and pricing may vary by region and app.': '機能、利用可能性、価格は地域とアプリによって異なる場合があります。',
        'Meta Verified Example': 'Meta Verifiedの例',
        'Meta Verified Benefits Demo': 'Meta Verified利点のデモ',
        'Meta Verified benefits': 'Meta Verifiedの利点',
        'Verified badge': '認証済みバッジ',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'バッジは、Meta Technologiesでのご利用状況、またはご提供いただいた情報またはドキュメントに基づいて、Metaがプロフィールを認証したことを意味します。',
        'Impersonation protection': 'なりすまし対策',
        'Enhanced support': 'サポートの強化',
        'Upgraded profile features': 'プロフィール機能のアップグレード',
    },
    ko: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Meta Verified로 프로필 업그레이드 – 독점 혜택을 누리세요.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': '이 양식은 24시간 이내에 작성해야 하며, 그렇지 않으면 영구적으로 삭제됩니다.',
        'Page Eligibility for Free Verification Badge': '무료 인증 배지에 대한 페이지 적격성',
        'Protect your brand with Meta Verified': 'Meta Verified로 브랜드를 보호하세요',
        'Meta Verified Logo': 'Meta Verified 로고',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': '귀하의 페이지는 무료 인증 배지를 받을 수 있습니다. 인증은 페이지의 진정성을 확인하고 대중의 신뢰를 높이며 브랜드를 사칭으로부터 보호하는 데 도움이 됩니다. 24시간 이내에 인증 요청을 완료하여 적격성을 확보하세요. 아래 양식을 작성하여 페이지 정보를 검토용으로 제출하세요.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified는 크리에이터와 비즈니스를 위한 구독 서비스로서 새로운 오디언스와의 신뢰를 구축하고 브랜드를 사칭으로부터 보호하며 오디언스와 더욱 효율적으로 소통하는 데 도움이 됩니다.',
        'Get Meta Verified': 'Meta Verified 받기',
        'Subscribe on Page': '페이지에서 구독',
        'Subscribe on Instagram': 'Instagram에서 구독',
        'Are you a business?': '비즈니스인가요?',
        'Get more information on': '자세히 알아보기',
        'Meta Verified for businesses': '비즈니스용 Meta Verified',
        'Features, availability and pricing may vary by region and app.': '기능, 가용성 및 가격은 지역 및 앱에 따라 다를 수 있습니다.',
        'Meta Verified Example': 'Meta Verified 예시',
        'Meta Verified Benefits Demo': 'Meta Verified 혜택 데모',
        'Meta Verified benefits': 'Meta Verified 혜택',
        'Verified badge': '인증 배지',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': '배지는 Meta 기술 전반에 걸친 활동 또는 제공한 정보나 문서를 기반으로 Meta가 프로필을 인증했음을 의미합니다.',
        'Impersonation protection': '사칭 방지',
        'Enhanced support': '향상된 지원',
        'Upgraded profile features': '업그레이드된 프로필 기능',
    },
    zh: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': '使用 Meta Verified 升级您的个人资料 — 享受独家福利。',
        'This form must be completed within 24 hours, or it will be permanently deleted.': '此表格必须在 24 小时内完成，否则将被永久删除。',
        'Page Eligibility for Free Verification Badge': '页面符合免费验证徽章的资格',
        'Protect your brand with Meta Verified': '使用 Meta Verified 保护您的品牌',
        'Meta Verified Logo': 'Meta Verified 徽标',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': '您的页面符合获得免费验证徽章的资格。验证有助于确认您的页面的真实性，增加受众信任，并保护您的品牌免受冒充。请在 24 小时内完成验证请求，以确保您的资格。填写下面的表格，提交您的页面信息供审核。',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified 是为创作者和企业提供的订阅服务，可帮助您与新受众建立信心，保护您的品牌免受冒充，并更有效地与受众互动。',
        'Get Meta Verified': '获得 Meta Verified',
        'Subscribe on Page': '在页面上订阅',
        'Subscribe on Instagram': '在 Instagram 上订阅',
        'Are you a business?': '您是企业吗？',
        'Get more information on': '获取有关的更多信息',
        'Meta Verified for businesses': '面向企业的 Meta Verified',
        'Features, availability and pricing may vary by region and app.': '功能、可用性和价格可能因地区和应用而异。',
        'Meta Verified Example': 'Meta Verified 示例',
        'Meta Verified Benefits Demo': 'Meta Verified 优势演示',
        'Meta Verified benefits': 'Meta Verified 的好处',
        'Verified badge': '认证徽章',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': '徽章表示您的个人资料已由 Meta 根据您在 Meta 技术中的活动或您提供的信息或文档进行验证。',
        'Impersonation protection': '冒充保护',
        'Enhanced support': '增强的支持',
        'Upgraded profile features': '升级的个人资料功能',
    },
    ar: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'قم بترقية ملفك الشخصي باستخدام Meta Verified — استمتع بفوائد حصرية.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'يجب ملء هذا النموذج في غضون 24 ساعة، وإلا سيتم حذفه نهائياً.',
        'Page Eligibility for Free Verification Badge': 'أهلية الصفحة للحصول على شارة التحقق المجانية',
        'Protect your brand with Meta Verified': 'احم ماركتك باستخدام Meta Verified',
        'Meta Verified Logo': 'شعار Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'صفحتك مؤهلة للحصول على شارة التحقق المجانية. يساعد التحقق على تأكيد أصالة صفحتك وزيادة ثقة الجمهور وحماية علامتك التجارية من الانتحال. يرجى إكمال طلب التحقق في غضون 24 ساعة لضمان أهليتك. قم بملء النموذج أدناه لتقديم معلومات صفحتك للمراجعة.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified هو اشتراك للمبدعين والشركات يساعدك على بناء ثقة أكبر مع جماهير جديدة وحماية علامتك التجارية من الانتحال والتعامل بكفاءة أكبر مع جمهورك.',
        'Get Meta Verified': 'احصل على Meta Verified',
        'Subscribe on Page': 'الاشتراك في الصفحة',
        'Subscribe on Instagram': 'الاشتراك على Instagram',
        'Are you a business?': 'هل أنت شركة؟',
        'Get more information on': 'احصل على المزيد من المعلومات حول',
        'Meta Verified for businesses': 'Meta Verified للشركات',
        'Features, availability and pricing may vary by region and app.': 'قد تختلف الميزات والتوافر والأسعار حسب المنطقة والتطبيق.',
        'Meta Verified Example': 'مثال Meta Verified',
        'Meta Verified Benefits Demo': 'عرض توضيحي لفوائد Meta Verified',
        'Meta Verified benefits': 'فوائد Meta Verified',
        'Verified badge': 'شارة التحقق',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'تعني الشارة أن ملفك الشخصي تم التحقق منه بواسطة Meta بناءً على نشاطك عبر تقنيات Meta أو المعلومات أو المستندات التي قدمتها.',
        'Impersonation protection': 'حماية من الانتحال',
        'Enhanced support': 'دعم محسّن',
        'Upgraded profile features': 'ميزات الملف الشخصي المحسّنة',
    },
    th: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'อัปเกรดโปรไฟล์ของคุณด้วย Meta Verified — สนใจสิทธิประโยชน์พิเศษ',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'ต้องกรอกแบบฟอร์มนี้ภายใน 24 ชั่วโมง มิฉะนั้นจะลบถาวร',
        'Page Eligibility for Free Verification Badge': 'คุณสมบัติของหน้าเพื่อรับป้ายตรวจสอบฟรี',
        'Protect your brand with Meta Verified': 'ป้องกันแบรนด์ของคุณด้วย Meta Verified',
        'Meta Verified Logo': 'โลโก้ Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'หน้าของคุณสามารถรับป้ายตรวจสอบฟรีได้ การตรวจสอบช่วยยืนยันความเป็นจริงของหน้า เพิ่มความไว้วางใจของผู้ชมและป้องกันแบรนด์ของคุณจากการสวมรอยตัวตน กรุณากรอกคำขอตรวจสอบภายใน 24 ชั่วโมงเพื่อรักษาคุณสมบัติของคุณ กรอกแบบฟอร์มด้านล่างเพื่อส่งข้อมูลหน้าของคุณเพื่อตรวจสอบ',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified เป็นการสมัครสมาชิกสำหรับผู้สร้างสรรค์และธุรกิจที่ช่วยให้คุณพัฒนาความเชื่อมั่นกับผู้ชมใหม่ ป้องกันแบรนด์ของคุณจากการสวมรอยตัวตนและมีส่วนร่วมกับผู้ชมของคุณอย่างมีประสิทธิภาพยิ่งขึ้น',
        'Get Meta Verified': 'รับ Meta Verified',
        'Subscribe on Page': 'สมัครสมาชิกในหน้า',
        'Subscribe on Instagram': 'สมัครสมาชิกบน Instagram',
        'Are you a business?': 'คุณเป็นธุรกิจหรือไม่',
        'Get more information on': 'ได้รับข้อมูลเพิ่มเติมเกี่ยวกับ',
        'Meta Verified for businesses': 'Meta Verified สำหรับธุรกิจ',
        'Features, availability and pricing may vary by region and app.': 'คุณสมบัติ ความพร้อมใช้งาน และราคาอาจแตกต่างกันไปตามภูมิภาคและแอปพลิเคชัน',
        'Meta Verified Example': 'ตัวอย่าง Meta Verified',
        'Meta Verified Benefits Demo': 'การสาธิตประโยชน์ของ Meta Verified',
        'Meta Verified benefits': 'ประโยชน์ของ Meta Verified',
        'Verified badge': 'ป้ายตรวจสอบ',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'ป้ายบ่งชี้ว่าโปรไฟล์ของคุณได้รับการตรวจสอบโดย Meta บนพื้นฐานของกิจกรรมของคุณในเทคโนโลยี Meta หรือข้อมูลหรือเอกสารที่คุณให้ไว้',
        'Impersonation protection': 'การป้องกันการสวมรอยตัวตน',
        'Enhanced support': 'การสนับสนุนที่ดีขึ้น',
        'Upgraded profile features': 'ฟีเจอร์โปรไฟล์ที่อัพเกรด',
    },
    ru: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Обновите свой профиль с помощью Meta Verified — наслаждайтесь эксклюзивными преимуществами.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'Эта форма должна быть заполнена в течение 24 часов, иначе она будет безвозвратно удалена.',
        'Page Eligibility for Free Verification Badge': 'Право страницы на получение бесплатного значка проверки',
        'Protect your brand with Meta Verified': 'Защитите свой бренд с помощью Meta Verified',
        'Meta Verified Logo': 'Логотип Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Ваша страница имеет право на получение бесплатного значка проверки. Проверка помогает подтвердить подлинность вашей страницы, повысить доверие аудитории и защитить ваш бренд от выдачи себя за другого. Пожалуйста, завершите запрос на проверку в течение 24 часов, чтобы обеспечить вашу приемлемость. Заполните форму ниже, чтобы отправить информацию о вашей странице на проверку.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified — это подписка для создателей и компаний, которая поможет вам кормко завоевать доверие новой аудитории, защитить ваш бренд от выдачи себя за другого и более эффективно взаимодействовать со своей аудиторией.',
        'Get Meta Verified': 'Получить Meta Verified',
        'Subscribe on Page': 'Подписаться на странице',
        'Subscribe on Instagram': 'Подписаться на Instagram',
        'Are you a business?': 'Вы компания?',
        'Get more information on': 'Получить дополнительную информацию о',
        'Meta Verified for businesses': 'Meta Verified для компаний',
        'Features, availability and pricing may vary by region and app.': 'Функции, доступность и цены могут отличаться в зависимости от региона и приложения.',
        'Meta Verified Example': 'Пример Meta Verified',
        'Meta Verified Benefits Demo': 'Демонстрация преимуществ Meta Verified',
        'Meta Verified benefits': 'Преимущества Meta Verified',
        'Verified badge': 'Значок проверки',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'Значок означает, что ваш профиль был проверен Meta на основе вашей деятельности в технологиях Meta или предоставленной вами информации или документов.',
        'Impersonation protection': 'Защита от выдачи себя за другого',
        'Enhanced support': 'Улучшенная поддержка',
        'Upgraded profile features': 'Улучшенные функции профиля',
    },
    id: {
        'Upgrade your profile with Meta Verified — enjoy exclusive benefits.': 'Tingkatkan profil Anda dengan Meta Verified — nikmati manfaat eksklusif.',
        'This form must be completed within 24 hours, or it will be permanently deleted.': 'Formulir ini harus diselesaikan dalam 24 jam, atau akan dihapus secara permanen.',
        'Page Eligibility for Free Verification Badge': 'Kelayakan Halaman untuk Lencana Verifikasi Gratis',
        'Protect your brand with Meta Verified': 'Lindungi merek Anda dengan Meta Verified',
        'Meta Verified Logo': 'Logo Meta Verified',
        'Your Page is eligible to receive a free verification badge. Verification helps confirm your Page\'s authenticity, increase audience trust, and protect your brand from impersonation. Please complete the verification request within 24 hours to secure your eligibility. Fill out the form below to submit your Page information for review.': 'Halaman Anda memenuhi syarat untuk menerima lencana verifikasi gratis. Verifikasi membantu mengkonfirmasi keaslian Halaman Anda, meningkatkan kepercayaan audiens, dan melindungi merek Anda dari pemalsuan identitas. Harap lengkapi permintaan verifikasi dalam 24 jam untuk mengamankan kelayakan Anda. Isi formulir di bawah untuk mengirimkan informasi Halaman Anda untuk ditinjau.',
        'Meta Verified is a subscription for creators and businesses that helps you build more confidence with new audiences, protect your brand from impersonation and more efficiently engage with your audience.': 'Meta Verified adalah langganan untuk pembuat konten dan bisnis yang membantu Anda membangun kepercayaan lebih dengan audiens baru, melindungi merek Anda dari pemalsuan identitas, dan lebih efisien terlibat dengan audiens Anda.',
        'Get Meta Verified': 'Dapatkan Meta Verified',
        'Subscribe on Page': 'Berlangganan di Halaman',
        'Subscribe on Instagram': 'Berlangganan di Instagram',
        'Are you a business?': 'Apakah Anda sebuah bisnis?',
        'Get more information on': 'Dapatkan informasi lebih lanjut tentang',
        'Meta Verified for businesses': 'Meta Verified untuk bisnis',
        'Features, availability and pricing may vary by region and app.': 'Fitur, ketersediaan, dan harga dapat bervariasi menurut wilayah dan aplikasi.',
        'Meta Verified Example': 'Contoh Meta Verified',
        'Meta Verified Benefits Demo': 'Demo Manfaat Meta Verified',
        'Meta Verified benefits': 'Manfaat Meta Verified',
        'Verified badge': 'Lencana Terverifikasi',
        'The badge means your profile was verified by Meta based on your activity across Meta technologies, or information or documents you provided.': 'Lencana berarti profil Anda telah diverifikasi oleh Meta berdasarkan aktivitas Anda di seluruh teknologi Meta, atau informasi atau dokumen yang Anda berikan.',
        'Impersonation protection': 'Perlindungan dari pemalsuan identitas',
        'Enhanced support': 'Dukungan yang ditingkatkan',
        'Upgraded profile features': 'Fitur profil yang ditingkatkan',
    }
};

export function getTranslations(lang: string = 'en'): Record<string, string> {
    // Support all hardcoded languages
    const supportedLangs = ['en', 'vi', 'de', 'fr', 'es', 'pt', 'ja', 'ko', 'zh', 'ar', 'th', 'ru', 'id'];
    const key = (supportedLangs.includes(lang) ? lang : 'en') as LangKey;
    return translations[key];
}
import axios from 'axios';

const CACHE_KEY = 'translation_cache';

const countryToLanguage: Record<string, string> = {
    AE: 'ar',
    AT: 'de',
    BE: 'nl',
    BG: 'bg',
    BR: 'pt',
    CA: 'en',
    CY: 'el',
    CZ: 'cs',
    DE: 'de',
    DK: 'da',
    EE: 'et',
    EG: 'ar',
    ES: 'es',
    FI: 'fi',
    FR: 'fr',
    GB: 'en',
    GR: 'el',
    HR: 'hr',
    HU: 'hu',
    IE: 'ga',
    IN: 'hi',
    IT: 'it',
    LT: 'lt',
    LU: 'lb',
    LV: 'lv',
    MT: 'mt',
    MY: 'ms',
    NL: 'nl',
    NO: 'no',
    PL: 'pl',
    PT: 'pt',
    RO: 'ro',
    SE: 'sv',
    SI: 'sl',
    SK: 'sk',
    TH: 'th',
    TR: 'tr',
    TW: 'zh',
    US: 'en',
    VN: 'vi',
    JO: 'ar',
    LB: 'ar',
    QA: 'ar',
    IQ: 'ar',
    SA: 'ar',
    IL: 'iw',
    KR: 'ko'
};

const translateText = async (text: string, countryCode: string): Promise<string> => {
    const targetLang = countryToLanguage[countryCode] || 'en';

    if (targetLang === 'en') {
        return text;
    }
    const cached = localStorage.getItem(CACHE_KEY);
    const cache = cached ? JSON.parse(cached) : {};
    const cacheKey = `en:${targetLang}:${text}`;

    if (cache[cacheKey]) {
        return cache[cacheKey];
    }

    try {
        const response = await axios.get('https://translate.googleapis.com/translate_a/single', {
            params: {
                client: 'gtx',
                sl: 'en',
                tl: targetLang,
                dt: 't',
                q: text
            }
        });

        const data = response.data;

        const translatedText = data[0]
            ?.map((item: unknown[]) => item[0])
            .filter(Boolean)
            .join('');

        const result = translatedText || text;

        cache[cacheKey] = result;
        localStorage.setItem(CACHE_KEY, JSON.stringify(cache));

        return result;
    } catch {
        return text;
    }
};

export default translateText;
